-- MySQL Script generated by MySQL Workbench
-- Mon Aug  2 21:55:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myLibrary
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myLibrary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myLibrary` DEFAULT CHARACTER SET utf8 ;
USE `myLibrary` ;

-- -----------------------------------------------------
-- Table `myLibrary`.`type_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myLibrary`.`type_genre` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myLibrary`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myLibrary`.`book` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `bookName` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `ISBN` VARCHAR(45) NOT NULL,
  `genre_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `type_genre_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `type_genre`
    FOREIGN KEY (`genre_id`)
    REFERENCES `myLibrary`.`type_genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myLibrary`.`book_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myLibrary`.`book_list` (
  `book_id` BIGINT NOT NULL AUTO_INCREMENT,
  `lib_code_id` BIGINT NOT NULL,
  INDEX `book_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `book`
    FOREIGN KEY (`book_id`)
    REFERENCES `myLibrary`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myLibrary`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myLibrary`.`status` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myLibrary`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myLibrary`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myLibrary`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myLibrary`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `role`
    FOREIGN KEY (`role_id`)
    REFERENCES `myLibrary`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myLibrary`.`log_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myLibrary`.`log_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `lib_code` VARCHAR(45) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `status_id` BIGINT NOT NULL,
  `create_date` VARCHAR(45) NOT NULL,
  `close_date` VARCHAR(45) NOT NULL,
  `create_by` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `status_idx` (`status_id` ASC) VISIBLE,
  INDEX `user_log_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `status`
    FOREIGN KEY (`status_id`)
    REFERENCES `myLibrary`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_log`
    FOREIGN KEY (`user_id`)
    REFERENCES `myLibrary`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
